dist: trusty
sudo: false
language: cpp

addons:
  apt:
    packages:
      - cmake-data
      - cmake
			- libboost-all-dev
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

script:
  - mkdir build && cd build
  - cmake ..
  - make check

before_install:
  - eval "${MATRIX_EVAL}"
