dist: trusty
sudo: false
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - boost-latest
          packages:
            - g++-7
            - cmake-data
            - cmake
            - libboost-all-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
            - boost-latest
          packages:
            - clang-5.0
            - cmake-data
            - cmake
            - libboost-all-dev
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

script:
  - eval "${MATRIX_EVAL}" && echo "CC=${CC} CXX=${CXX}" && mkdir build && cd build && cmake .. && make check

before_install:
  - eval "${MATRIX_EVAL}"
