name: MacOS

on:
  push:
    branches-ignore: dev
  pull_request:
    branches-ignore: dev
    

jobs:
  build:
    runs-on: [macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Build and Test
        working-directory: build
        run: ./ci_test.sh
        
