name: MacOS

on:
  push:
    branches-ignore: dev
  pull_request:
    branches-ignore: dev
    

jobs:
  build:
    runs-on: [macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Build and Test
        working-directory: build
        shell: bash
        run: |
          cmake -DCMAKE_BUILD_TYPE=Debug ..
          cmake --build . --config Debug --target full -j 2
          ctest -C Debug
        
