name: Ubuntu

on:
  push:
    branches-ignore: dev
  pull_request:
    branches-ignore: dev
    

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Add LLVM Repo
      run: sudo sh ./ci_llvm_apt.sh
    - name: Download & Build Dependencies
      run: |        
        sudo apt update
        sudo apt install clang-9 lldb-9 lld-9
    - name: Build and Test
      run: ./ci_test.sh
       
